language: r
r:
  - release
  - devel
cache: packages

r_packages:
  - kableExtra
  - covr
  - pkgdown

after_success:
  - Rscript -e 'covr::coveralls()'


notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
