language: r
r:
  - oldrel
  - release
  - devel
cache: packages

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
  
notifications:
  email:
    on_success: change
    on_failure: change