language: r
r:
  - release
  - devel
cache: packages


before_install:
  - sudo apt-get update
  - sudo apt-get -y install libharfbuzz-dev libfribidi-dev
  
  
r_packages:
  - kableExtra
  - covr
  - pkgdown

after_success:
  - Rscript -e 'covr::coveralls()'


notifications:
  email:
    on_success: change
    on_failure: change